pipeline {
    agent any
    environment {
        JAR_FILE = ''  // Initialize an environment variable to store the JAR file name
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                sh 'ls -l target'
                
                // Capture the exact filename of the generated JAR file
                script {
                    JAR_FILE = sh(script: "ls target/*.jar", returnStdout: true).trim()
                    echo "Generated JAR file: ${JAR_FILE}"
                }
                
                // Set permissions to the JAR file
                sh "chmod 777 ${JAR_FILE}"
                
                // Verify permissions were set
                sh 'ls -l target'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                script {
                    // Pass the JAR file name to the deliver.sh script
                    sh "./jenkins/scripts/deliver.sh ${JAR_FILE}"
                }
            }
        }
    }
}
